### PR TITLE
Add shortcut to find and returns first helpfile matching topics

### PR DESCRIPTION
**Pull request by clagiordano**
This PR adds an alternative method to search and returns first helpfile matching topic.

### CODE REVIEW

**Comment by shawncplus** [comment]
I'd prefer the `return;` to `return null;`. I try to reserve `return;` only for void methods but this method's return type is `?string`

**Comment by shawncplus** [comment]
Almost, the docblock isn't quite right :)

**Comment by clagiordano** [comment]
@shawncplus Do you want a docblock without description?

**Comment by shawncplus** [comment]
No, the description is fine. See this comment https://github.com/RanvierMUD/core/pull/44#issuecomment-461895287 The param type should be `@param {string}`, separately the return type should be `@return {?string}`

**Comment by clagiordano** [comment]
Oh, sure I forgot search params, fine.

**Comment by shawncplus** [comment]
Excellent, thank you

**Comment by clagiordano** [comment]
Thanks to you, great work!

**Pull request merged**
