### PR TITLE
Return spawned item

### PR DESCRIPTION
**Pull request by nahilep**

### CODE REVIEW

**Comment by markscho** [comment]
You should be updating the comment too:
   * @return {Item} newItem

**Comment by markscho** [comment]
While we're at it, the reference to `this.area` is wrong.  According to Item's class definition:
` * @property {Area}    area        Area the item belongs to (warning: this is not the area is currently in but the`
` *                                 area it belongs to on a fresh load)`
Oddly, it appears that of Core's 6 calls to ItemFactory.create(), it only gets this right twice.  Here, it should be referencing area as:  `state.AreaManager.getAreaByReference(entityRef)`

**Comment by nahilep** [comment]
Updated the doc comment.

Regarding `this.area` not being correct: I am not quite sure that this is not correct. If I create an item programmatically in a room it should have its area set to this rooms area. I am not quite sure for what the area property is used anyway so I would like to hear from @shawncplus if this is indeed an issue.

Also I think that would be an extra PR to keep it with one fix/feature/improvement per PR

**Comment by shawncplus** [comment]
@markscho seems to be correct. When an item is initially loaded via a bundle, from an `Inventory`, or `Player` equipment it correctly sets area to be the item's originating area. But during `Room#spawnItem` it incorrectly sets it to the Room's area which may or may not be correct. During `Npc#hydrate` for default inventory/equipment it also sets the item area to the NPC's area which may or may not be correct. Player equipment is technically correct but for the wrong reasons. It's doing `state.AreaManager.getArea(itemDef.area)` instead of doing `state.AreaManager.getAreaByReference(itemDef.entityReference)`

**Comment by nahilep** [comment]
It seems to me that this is a whole new issue and not in the scope of this pull request.

But since I am not quite sure that I understand it, I have one last question: Is the only reason for the area property to know in which area an item is defined in?

**Comment by shawncplus** [comment]
yeah definitely not in the scope of this pull request, just wanted to clear up that confusion.

> Is the only purpose of the area property to know in which area an item is defined in?

Yes

**Pull request merged**
