### PR TITLE
Proposal fix for issue #55

### PR DESCRIPTION
**Pull request by clagiordano**
Adds default value for optional callback playerCallback, then on emit call it with players data

### CODE REVIEW

**Comment by seanohue** [comment]
This fix works, but there is another PR that fixes it by removing the callback entirely. Not sure if folks have a preference.

**Comment by clagiordano** [comment]
I tried to be conservative with actual core code with this fix, if you prefer can close and/or reject this PR
Personally I prefer an optional callback instead to drop it.

**Comment by seanohue** [comment]
Unfortunately I don't have the admin powers needed to merge, close, or reject PRs. Also mainly wanted to comment to see if others had a preference.

**Comment by shawncplus** [comment]
Touched code no longer exists

**Pull request closed without merging**
