### PR TITLE
Add ability to get the exit by the target room

### PR DESCRIPTION
**Pull request by atarsha**
I'm finding a number of cases where I know the room I'm in, and the room I'm going to, or vice versa, and needing to determine the direction.

Rather than repeating a bunch of looping code, this feels like something useful within the core API.

If not, let me know and I'll just find a place to cram something similar into a bundle.

### CODE REVIEW

**Comment by atarsha** [comment]
My various PRs today are all around supporting listeners in player-events that allow those events to trigger a sayAt something like "Npcname has arrived."

Using the example bundle: `bundle-example-npc-behaviors`:

ranvier-wander was using moveTo which emits npcLeave to this.room, and npcEnter to the nextRoom.

However in this case I want different movement message because it's a different type of movement.

"Npcname has wandered in from the west."

I can do this by not calling moveTo, and instead doing something like the following:

```
//this.moveTo(randomRoom); // turned off so I can control my text

      // The following code replaces moveTo above so we can fully control the departure/arrival messages since npcEnter/npcLeave will not be emitted
			Broadcast.sayAt(this.room, `${this.name} wanders ${roomExit.direction}.`);

			const newRoomExit = randomRoom.getExitToRoom(this.room);
			if (newRoomExit) {
				Broadcast.sayAt(randomRoom, `${this.name} wanders in from the ${newRoomExit.direction}.`);
      } else {
				Broadcast.sayAt(randomRoom, `${this.name} wanders in.`);
      }

			this.room.removeNpc(this);
			this.room = randomRoom;
      randomRoom.addNpc(this);
```

**Comment by shawncplus** [comment]
The npcEnter/npcLeave events not getting emitted would be Very Bad as wandering NPCs would no longer interact correctly with any scripts listening for those events. It seems it would be easier to just have the player movement command handling broadcast those messages and have the npc wander behavior broadcast different messages.

Both the wander behavior and the code that handles player movement commands already know the exit the NPC is moving through so there's no need to modify core with that extra method

**Comment by atarsha** [comment]
`The npcEnter/npcLeave events not getting emitted would be Very Bad as wandering NPCs would no longer interact correctly with any scripts listening for those events.`

Good catch. That makes total sense to me and I hadn’t considered that.

The problem remains, exit.direction is contextual.

In the case of wander, it does a this.room.getExits() then selects a random exit. In this case I know the direction I’m going however when I get there I don’t know the direction I came from.

The only way I can do that is by looping through the exits from the new room and comparing them against the room I came from until I find a match, which is why the code above is handy.

**Comment by shawncplus** [comment]
I think your function is useful though something to note is may not always have an exit. A -> B might be 'east' but B might not have an reciprocal exit back to A to the west. B might not have any exits at all. Or consider this scenario: There's fast travel system where in any room of the game I can `recall` back to a home point. Now say that I start in my home point and move one room west. If I then used `recall` your finding an exit code would get a false positive saying I walked from the west when I didn't, I magically teleported into the room and just so happened to be coming from the room to the west.

I personally think it'd be better to just broadcast the messages directly from the wander code and the player movement code than trying to handle them in the very generic (npc/player)enter/Leave events. In the recall scenario described above I could just add specific broadcasts to my recall command.

**Comment by atarsha** [comment]
We are in agreement that broadcasting from the actual movement code is the better solution.

That said I think even doing it that way still requires this code. Here’s why:
Like you said, we can’t make assumptions that A -> B has a recipricol exit in the reverse, in fact it’s posible it was east to get here and up to go back, so I can’t just say (via code) “if I went east to get there, I came from the west to get here.”
Instead, I have to loop through all the exits compare the exit’s destination to the previous room, and if it’s a match, that is the direction I arrived from. As for no such exit existing: in my agreeably not-ideal code above you can see an if statement wrapping the output of the method to deal with the scenario.

Even if my movement code broadcasts the message, which we are now in agreement is ideal, it will need to execute this code, because while I know to which room I’m going, I still need to retrieve the exit to get the direction. By following the paradigm that it’s the responsibility of every implementation of movement code itself rather than a centralized location to do the broadcasting, I’d posit that a centralized method of retrieving the exit to the previous room is proper application of DRY, or else we (or at least I) will be repeating code in every movement command to accomplish this.

If you don’t feel that the ability to retrieve the exit for a given room is core functionality, let me know and I’ll create a movement bundle to deal with all my movement specific commands, behaviors and such so that I can centralize this sort of code.

**Comment by shawncplus** [comment]
I'm going to merge it in but just as a heads up this won't actually be published to npm for a while since it would be part of a minor release so you may end up having to put it in your bundle code anyway.

**Comment by atarsha** [comment]
Just as a follow up, I ended up creating a bundle to centralize the code for finding the direction of an exit from a room to another room on my end, and moved the broadcasting to the individual commands (although interestingly enough, the standard directional moves use the event emitter and a listener to do the broadcasting the same way I was heading -- I'll probably re-work this on my end as well.)

While I think this PR makes sense, I've now worked around it, so feel free to pass on it.

**Comment by atarsha** [comment]
Heh, we were typing at the same time :/

**Pull request merged**
